USE [master]
GO

/****** Object:  Database [DB_T]    Script Date: 3/18/2020 10:44:32 AM ******/
CREATE DATABASE [DB_T]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_T', FILENAME = N'F:\Microsoft SQL Server\MSSQL11.QADEVSQL12\MSSQL\DATA\DB_T.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DB_T_log', FILENAME = N'F:\Microsoft SQL Server\MSSQL11.QADEVSQL12\MSSQL\DATA\DB_T_log.ldf' , SIZE = 53248KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_T].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_T] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_T] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_T] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_T] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_T] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_T] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_T] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_T] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_T] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_T] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_T] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_T] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_T] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_T] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_T] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_T] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_T] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_T] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_T] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_T] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_T] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_T] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_T] SET RECOVERY FULL 
GO

ALTER DATABASE [DB_T] SET  MULTI_USER 
GO

ALTER DATABASE [DB_T] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_T] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_T] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_T] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DB_T] SET  READ_WRITE 
GO


